[package]
name = "rust_csv"
version = "0.1.0"
authors = ["yujiimt <yujiimuta0572@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.0.0-beta.1"
serde = "1"
serde_derive = "1"